services:
  mongo:
    image: mongo:6
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    networks:
      - MERNApp

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    env_file: 
      - ./server/.env
    volumes:
      - ./server:/app
      - backend_node_modules:/app/node_modules
    networks:
      - MERNApp
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    command: npm run dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - MERNApp
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

volumes:
  mongo_data:
  backend_node_modules:
  frontend_node_modules:

networks:
  MERNApp:
    driver: bridge
